import 'package:get/get.dart';
import 'package:paycron/controller/all_company_controller/all_bussiness_controller.dart';
import 'package:paycron/controller/all_company_controller/businessProfileController.dart';
import 'package:paycron/controller/auth/authController.dart';
import 'package:paycron/controller/auth/forgot_controller.dart';
import 'package:paycron/controller/billing_controller/BillingInformationController.dart';
import 'package:paycron/controller/billing_controller/customer_billing.dart';
import 'package:paycron/controller/billing_controller/upgrade_plan_controller.dart';
import 'package:paycron/controller/common_controller.dart';
import 'package:paycron/controller/dashboard/create_payment_controller.dart';
import 'package:paycron/controller/dashboard/merchant_controller/change_password_controller.dart';
import 'package:paycron/controller/dashboard/merchant_controller/merchant_controller.dart';
import 'package:paycron/controller/dashboard/overallStatistic_controller.dart';
import 'package:paycron/controller/dashboard/report_overview_controller.dart';
import 'package:paycron/controller/dashboard/submember_controller/active_submember_controller.dart';
import 'package:paycron/controller/dashboard/submember_controller/all_submember_controller.dart';
import 'package:paycron/controller/dashboard/submember_controller/deleteRequest_submember_controller.dart';
import 'package:paycron/controller/dashboard/submember_controller/delete_submember_controller.dart';
import 'package:paycron/controller/dashboard/user_main_dashboard_controller.dart';
import 'package:paycron/controller/drawer_Controller/all_transaction_controller/itemTransactionDetailController.dart';
import 'package:paycron/controller/drawer_Controller/all_transaction_controller/verified_transaction_controller.dart';
import 'package:paycron/controller/drawer_Controller/all_transaction_controller/all_transaction_controller.dart';
import 'package:paycron/controller/drawer_Controller/all_transaction_controller/cancel_transaction_controller.dart';
import 'package:paycron/controller/drawer_Controller/all_transaction_controller/delete_transaction_controller.dart';
import 'package:paycron/controller/drawer_Controller/all_transaction_controller/download_transaction_controller.dart';
import 'package:paycron/controller/drawer_Controller/all_transaction_controller/new_transaction_controller.dart';
import 'package:paycron/controller/drawer_Controller/all_transaction_controller/reimbursement_transaction_controller.dart';
import 'package:paycron/controller/drawer_Controller/customer_controller/CustomerDetailViewController.dart';
import 'package:paycron/controller/drawer_Controller/customer_controller/Inactive_controller.dart';
import 'package:paycron/controller/drawer_Controller/customer_controller/active_controller.dart';
import 'package:paycron/controller/drawer_Controller/customer_controller/add_customer_controller.dart';
import 'package:paycron/controller/drawer_Controller/customer_controller/all_controller.dart';
import 'package:paycron/controller/drawer_Controller/invoice_controller/add_invoice_controller.dart';
import 'package:paycron/controller/drawer_Controller/invoice_controller/all_invoice_controller.dart';
import 'package:paycron/controller/drawer_Controller/invoice_controller/cancel_invoice_controller.dart';
import 'package:paycron/controller/drawer_Controller/invoice_controller/complete_invoice_controller.dart';
import 'package:paycron/controller/drawer_Controller/invoice_controller/delete_invoice_controller.dart';
import 'package:paycron/controller/drawer_Controller/invoice_controller/download_invoice_controller.dart';
import 'package:paycron/controller/drawer_Controller/invoice_controller/invoice_incomplete_controller.dart';
import 'package:paycron/controller/drawer_Controller/invoice_controller/reimbursement_invoice_controller.dart';
import 'package:paycron/controller/drawer_Controller/invoice_controller/verified_invoice_controller.dart';
import 'package:paycron/controller/drawer_Controller/product_controller/Inactive_Product_controller.dart';
import 'package:paycron/controller/drawer_Controller/product_controller/ProductDetailViewController.dart';
import 'package:paycron/controller/drawer_Controller/product_controller/active_product_controller.dart';
import 'package:paycron/controller/drawer_Controller/product_controller/addProductController.dart';
import 'package:paycron/controller/drawer_Controller/product_controller/all_product_controller.dart';
import 'package:paycron/controller/drawer_Controller/subscriptions_controller/add_subscription_controller.dart';
import 'package:paycron/controller/drawer_Controller/subscriptions_controller/all_subscriptions_controller.dart';
import 'package:paycron/controller/drawer_Controller/subscriptions_controller/cancel_subscriptions_controller.dart';
import 'package:paycron/controller/drawer_Controller/subscriptions_controller/delete_subscriptions_controller.dart';
import 'package:paycron/controller/drawer_Controller/subscriptions_controller/download_subscriptions_controller.dart';
import 'package:paycron/controller/drawer_Controller/subscriptions_controller/new_subscriptions_controller.dart';
import 'package:paycron/controller/drawer_Controller/subscriptions_controller/reimbursement_subscriptions_controller.dart';
import 'package:paycron/controller/drawer_Controller/subscriptions_controller/subscription_scheduled_controller.dart';
import 'package:paycron/controller/drawer_Controller/subscriptions_controller/verified_subscriptions_controller.dart';
import 'package:paycron/controller/drawer_Controller/virtual_terminal_comtroller/Verified_virtual_terminal_controller.dart';
import 'package:paycron/controller/drawer_Controller/virtual_terminal_comtroller/all_virtual_terminal_controller.dart';
import 'package:paycron/controller/drawer_Controller/virtual_terminal_comtroller/cancel_virtual_terminal_controller.dart';
import 'package:paycron/controller/drawer_Controller/virtual_terminal_comtroller/delete_virtual_terminal_controller.dart';
import 'package:paycron/controller/drawer_Controller/virtual_terminal_comtroller/download_virtual_terminal_controller.dart';
import 'package:paycron/controller/drawer_Controller/virtual_terminal_comtroller/new_virtual_terminal_controller.dart';
import 'package:paycron/controller/drawer_Controller/virtual_terminal_comtroller/reimbursement_virtual_terminal_controller.dart';
import 'package:paycron/controller/fund_controller/all_fund_controller.dart';
import 'package:paycron/controller/fund_controller/funds_controller.dart';
import 'package:paycron/controller/fund_controller/pending_controller.dart';
import 'package:paycron/controller/fund_controller/successful_controller.dart';
import 'package:paycron/controller/fund_controller/unsuccessful_controller.dart';
import 'package:paycron/controller/variable_controller.dart';

class InitialBinding extends Bindings {
  @override
  void dependencies() {
    // Register controllers here
    Get.put(VariableController());
    Get.put(CommonController());
    Get.put(OverallStatisticController());
    Get.put(ReportOverviewController());
    Get.put(AuthController());
    Get.put(AllBussinessController());
    Get.put(MainDashboardController());
    Get.put(CreatePaymentController());
    Get.put(AllTabController());
    Get.put(ActiveController());
    Get.put(InActiveController());
    Get.put(CustomerDetailViewController());
    Get.put(AddCustomerController());
    Get.put(AllTabProductController());
    Get.put(ActiveProductController());
    Get.put(InActiveProductController());
    Get.put(ProductDetailViewController());
    Get.put(AllTransactionController());
    Get.put(NewTransactionController());
    Get.put(VerifiedTransactionController());
    Get.put(DownloadTransactionController());
    Get.put(CancelTransationController());
    Get.put(DeleteTransactionController());
    Get.put(ReimbursementTransactionController());
    Get.put(AllVirtualTerminalController());
    Get.put(CancelVirtualTerminalController());
    Get.put(DeleteVirtualTerminalController());
    Get.put(DownloadVirtualTerminalController());
    Get.put(NewVirtualTerminalController());
    Get.put(ReimbursementVirtualTerminalController());
    Get.put(VerifiedVirtualTerminalController());
    Get.put(AllSubmemberController());
    Get.put(DeleteRequestSubmemberController());
    Get.put(DeleteSubmemberController());
    Get.put(ActiveSubmemberController());
    Get.put(AllSubscriptionsController());
    Get.put(CancelSubscriptionsController());
    Get.put(DeleteSubscriptionsController());
    Get.put(DownloadSubscriptionsController());
    Get.put(NewSubscriptionsController());
    Get.put(ReimbursementSubscriptionsController());
    Get.put(ScheduledSubscriptionsController());
    Get.put(VerifiedSubscriptionsController());
    Get.put(AllInvoiceController());
    Get.put(CancelInvoiceController());
    Get.put(DeleteInvoiceController());
    Get.put(DownloadInvoiceController());
    Get.put(CompleteInvoiceController());
    Get.put(ReimbursementInvoiceController());
    Get.put(IncompleteInvoiceController());
    Get.put(VerifiedInvoiceController());
    Get.put(ItemTransactionDetailsController());
    Get.put(AddProductController());
    Get.put(CustomerBillingController());
    Get.put(FundController());
    Get.put(AllFundsController());
    Get.put(PendingFundsController());
    Get.put(SuccessfulFundsController());
    Get.put(UnsuccessfulFundsController());
    Get.put(BusinessProfileController());
    Get.put(BillingInformationController());
    Get.put(UpgradePlanController());
    Get.put(AddInvoiceController());
    Get.put(AddSubscriptionController());
    Get.put(MerchantController());
    Get.put(ChangePasswordController());
    Get.put(ForgotPasswordController());
  }
}
