class MyUrls {
  ///--------------------------- Test Url ----------------------------
  static String BASE_URL ="https://paycron.amazing7studios.com"; // Public Test Url
  static String login = "auth/api/login";
  static String allbusiness = "merchant/api/allbusiness";
  static String filterCustomer = "merchant/api/filter-customer";
  static String singleCustomer = "merchant/api/singlecustomer";
  static String singleProduct = "merchant/api/singleproduct";
  static String allTransactionsByCustomerId = "merchant/api/alltransactionsbycustid";
  static String addCustomer = "merchant/api/addcustomer";
  static String filterProduct = "merchant/api/filter-product";
  static String checkRoutingNumber = "merchant/api/checkroutingnumber";
  static String addSingleAccount = "merchant/api/addcustomersinglebank";
  static String customerList = "merchant/api/customerlist";
  static String allTransactionDetail = "merchant/api/alltransactions";
  static String allVTDetail = "merchant/api/filter-vt";
  static String allInvoiceDetail = "merchant/api/filter-invoice";
  static String allSubscriptionDetail = "merchant/api/filter-subscription";
  static String singlePayment = "merchant/api/singlepayment";
  static String verifyPayment = "merchant/api/verifypayments";
  static String deletePayment = "merchant/api/deleterequestpayment";
  static String cancelPayment = "merchant/api/paymentstatuschange";
  static String downloadPayment = "merchant/api/downloadcheck";
  static String addProduct = "merchant/api/addproduct";
  static String fundsOfBusiness = "merchant/api/fundsofbusiness";
  static String getAllGateway = "merchant/api/getallgateways";
  static String allFilterFunds = "merchant/api/filterfunds";
  static String singleBusiness = "merchant/api/singlebusiness";
  static String filterBilling = "merchant/api/filter-billing";
  static String getAllPlans = "merchant/api/getallplans";
  static String getSinglePlans = "merchant/api/getoneplan";
  static String allTransactionsCountByCustomerNew = "merchant/api/alltransactionscountbycustnew";
  static String productList = "merchant/api/productlist";
  static String updatePlane = "merchant/api/updateplan";
  static String singleUser = "auth/api/singleuser";
  static String allSubmemberByUser = "merchant/api/allsubmembersbyuser";
  static String addPayment = "merchant/api/add-payment";
  static String addInvoice = "merchant/api/add-invoice";
  static String addSubscription = "merchant/api/add-subscription";
  static String updateCustomer = "merchant/api/updatecustomer";
  static String updateCustomerBank = "merchant/api/updatecustomerbank";
  static String changeBankStatus = "merchant/api/changebankstatus";
  static String forgotPassword = "auth/api/forgotpassword";
  static String addFundsByBusiness = "merchant/api/addfundbybusiness";
  static String sendInvoice = "merchant/api/sendinvoice";
  static String resetPassword = "merchant/api/resetpasswordmerch";
  static String updateProduct = "merchant/api/updateproduct";
}
